# Generated by Django 4.2.10 on 2025-03-04 00:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('COWORKER', 'Coworker')], default='COWORKER', help_text='User role in the system', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title (minimum 3 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task', max_length=1000)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='TODO', help_text='Current status of the task', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', help_text='Task priority level', max_length=20)),
                ('task_type', models.CharField(choices=[('FEATURE', 'Feature'), ('BUG', 'Bug'), ('IMPROVEMENT', 'Improvement'), ('DOCUMENTATION', 'Documentation'), ('OTHER', 'Other')], default='OTHER', help_text='Type of task', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, help_text='When this task is due', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the task was created')),
                ('last_edited', models.DateTimeField(auto_now=True, help_text='When the task was last modified')),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the review process', max_length=500)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Coworker assigned to this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Administrator who created this task', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-priority', 'due_date', 'created_at'],
            },
        ),
    ]
